-- use securityadmin to create the database role
USE ROLE SECURITYADMIN;
-- use database to create the database role
USE DATABASE GOVERNANCE;

-- create database role for modify access
CREATE DATABASE ROLE IF NOT EXISTS GOVERNANCE.COMMON_MODIFY
    COMMENT = 'Role for modify/insert/delete access to governance common schema'
;

-- database role grants
-- grant read role to modify role
GRANT DATABASE ROLE GOVERNANCE.COMMON_READ TO DATABASE ROLE GOVERNANCE.COMMON_MODIFY;

-- usage grants
-- procedures
GRANT USAGE ON ALL PROCEDURES IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_MODIFY;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_MODIFY;

-- sequences
GRANT USAGE ON ALL SEQUENCES IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_MODIFY;
GRANT USAGE ON FUTURE SEQUENCES IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_MODIFY;

-- select grants
-- stream
GRANT SELECT ON ALL STREAMS IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_MODIFY;
GRANT SELECT ON FUTURE STREAMS IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_MODIFY;

-- insert grants
-- tables
GRANT INSERT ON ALL TABLES IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_MODIFY;
GRANT INSERT ON FUTURE TABLES IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_MODIFY;

-- iceberg tables
GRANT INSERT ON ALL ICEBERG TABLES IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_MODIFY;
GRANT INSERT ON FUTURE ICEBERG TABLES IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_MODIFY;

-- update grants
-- tables
GRANT UPDATE ON ALL TABLES IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_MODIFY;
GRANT UPDATE ON FUTURE TABLES IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_MODIFY;

-- iceberg tables
GRANT UPDATE ON ALL ICEBERG TABLES IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_MODIFY;
GRANT UPDATE ON FUTURE ICEBERG TABLES IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_MODIFY;

-- delete grants
-- tables
GRANT DELETE ON ALL TABLES IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_MODIFY;
GRANT DELETE ON FUTURE TABLES IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_MODIFY;
-- iceberg tables
GRANT DELETE ON ALL ICEBERG TABLES IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_MODIFY;
GRANT DELETE ON FUTURE ICEBERG TABLES IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_MODIFY;

-- truncate grants
-- tables
GRANT TRUNCATE ON ALL TABLES IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_MODIFY;
GRANT TRUNCATE ON FUTURE TABLES IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_MODIFY;
-- iceberg tables
GRANT TRUNCATE ON ALL ICEBERG TABLES IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_MODIFY;
GRANT TRUNCATE ON FUTURE ICEBERG TABLES IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_MODIFY;

-- read grants
-- stages
GRANT READ ON ALL STAGES IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_MODIFY;
GRANT READ ON FUTURE STAGES IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_MODIFY;

-- write grants
-- stages
GRANT WRITE ON ALL STAGES IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_MODIFY;
GRANT WRITE ON FUTURE STAGES IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_MODIFY;
