-- use securityadmin to create the database role
USE ROLE SECURITYADMIN;
-- use database to create the database role
USE DATABASE GOVERNANCE;

-- create database role for read access
CREATE DATABASE ROLE IF NOT EXISTS GOVERNANCE.COMMON_READ
    COMMENT = 'Role for read-only access to governance common schema'
;

-- database role grants
-- allows the role to use the database
GRANT USAGE ON DATABASE GOVERNANCE TO DATABASE ROLE GOVERNANCE.COMMON_READ;
-- allows the role to use the schema
GRANT USAGE ON SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_READ;

-- select grants
-- tables
GRANT SELECT ON ALL TABLES IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_READ;
GRANT SELECT ON FUTURE TABLES IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_READ;
-- dynamic tables
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_READ;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_READ;
-- external tables
GRANT SELECT ON ALL EXTERNAL TABLES IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_READ;
GRANT SELECT ON FUTURE EXTERNAL TABLES IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_READ;
-- iceberg tables
GRANT SELECT ON ALL ICEBERG TABLES IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_READ;
GRANT SELECT ON FUTURE ICEBERG TABLES IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_READ;
-- interactive tables
GRANT SELECT ON ALL INTERACTIVE TABLES IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_READ;
GRANT SELECT ON FUTURE INTERACTIVE TABLES IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_READ;
-- online feature_table
GRANT SELECT ON ALL ONLINE FEATURE TABLES IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_READ;
GRANT SELECT ON FUTURE ONLINE FEATURE TABLES IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_READ;
--views
GRANT SELECT ON ALL VIEWS IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_READ;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_READ;
-- materialized views
GRANT SELECT ON ALL MATERIALIZED VIEWS IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_READ;
GRANT SELECT ON FUTURE MATERIALIZED VIEWS IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_READ;

-- read grants
-- image repositories
GRANT READ ON ALL IMAGE REPOSITORIES IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_READ;
GRANT READ ON FUTURE IMAGE REPOSITORIES IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_READ;
-- stages
GRANT READ ON ALL STAGES IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_READ;
GRANT READ ON FUTURE STAGES IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_READ;

-- usage grants (excluding database & schema grant)
-- datasets
GRANT USAGE ON ALL DATASETS IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_READ;
GRANT USAGE ON FUTURE DATASETS IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_READ;
-- file formats
GRANT USAGE ON ALL FILE FORMATS IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_READ;
GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_READ;
-- functions
GRANT USAGE ON ALL FUNCTIONS IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_READ;
GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_READ;
-- stages
GRANT USAGE ON ALL STAGES IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_READ;
GRANT USAGE ON FUTURE STAGES IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_READ;

/* optional grants
GRANT USAGE ON ALL STREAMLITS IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_READ;
GRANT USAGE ON FUTURE STREAMLITS IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_READ;

GRANT USAGE ON ALL WORKSPACES IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_READ;
GRANT USAGE ON FUTURE WORKSPACES IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_READ;

GRANT USAGE ON ALL NOTEBOOKS IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_READ;
GRANT USAGE ON FUTURE NOTEBOOKS IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_READ;

GRANT USAGE ON ALL PROCEDURES IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_READ;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_READ;
*/
