-- use securityadmin to create the database role
USE ROLE SECURITYADMIN;
-- use database to create the database role
USE DATABASE GOVERNANCE;

-- create database role for build access
CREATE DATABASE ROLE IF NOT EXISTS GOVERNANCE.COMMON_BUILD
    COMMENT = 'Role for build access to governance common schema'
;

-- database role grants
-- grant read role to build role
GRANT DATABASE ROLE GOVERNANCE.COMMON_READ TO DATABASE ROLE GOVERNANCE.COMMON_BUILD;

-- usage grants
-- models
GRANT USAGE ON ALL MODELS IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_BUILD;
GRANT USAGE ON FUTURE MODELS IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_BUILD;
-- notebooks
--GRANT USAGE ON ALL NOTEBOOKS IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_BUILD;
--GRANT USAGE ON FUTURE NOTEBOOKS IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_BUILD;
-- workspaces
GRANT USAGE ON ALL WORKSPACES IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_BUILD;
GRANT USAGE ON FUTURE WORKSPACES IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_BUILD;

-- read grants
-- artifact repositories
GRANT READ ON ALL ARTIFACT REPOSITORIES IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_BUILD;
GRANT READ ON FUTURE ARTIFACT REPOSITORIES IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_BUILD;
-- workspaces
GRANT READ ON ALL WORKSPACES IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_BUILD;
GRANT READ ON FUTURE WORKSPACES IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_BUILD;

-- create grants
-- views
GRANT CREATE VIEW ON SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_BUILD;
-- materialized views
GRANT CREATE MATERIALIZED VIEW ON SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_BUILD;
-- datasets
GRANT CREATE DATASET ON SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_BUILD;
-- notebooks
GRANT CREATE NOTEBOOK ON SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_BUILD;
-- workspaces
GRANT CREATE WORKSPACE ON SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_BUILD;
