-- use securityadmin to create the database role
USE ROLE SECURITYADMIN;
-- use database to create the database role
USE DATABASE GOVERNANCE;

-- create database role for engineer access
CREATE DATABASE ROLE IF NOT EXISTS GOVERNANCE.COMMON_ENGINEER
    COMMENT = 'Role for engineer/architect access to governance common schema'
;

-- database role grants
-- grant read role to engineer role
GRANT DATABASE ROLE GOVERNANCE.COMMON_READ TO DATABASE ROLE GOVERNANCE.COMMON_ENGINEER;
-- grant modify role to engineer role
GRANT DATABASE ROLE GOVERNANCE.COMMON_MODIFY TO DATABASE ROLE GOVERNANCE.COMMON_ENGINEER;

-- create grants
-- artifact repositories
GRANT CREATE ARTIFACT REPOSITORY ON SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_ENGINEER;
-- backup sets
GRANT CREATE BACKUP SET ON SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_ENGINEER;
-- dynamic tables
GRANT CREATE DYNAMIC TABLE ON SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_ENGINEER;
-- experiments
GRANT CREATE EXPERIMENT ON SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_ENGINEER;
-- external tables
GRANT CREATE EXTERNAL TABLE ON SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_ENGINEER;
-- file formants
GRANT CREATE FILE FORMAT ON SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_ENGINEER;
-- functions
GRANT CREATE FUNCTION ON SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_ENGINEER;
-- hybrid tables
GRANT CREATE HYBRID TABLE ON SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_ENGINEER;
-- iceberg tables
GRANT CREATE ICEBERG TABLE ON SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_ENGINEER;
-- image repositories
GRANT CREATE IMAGE REPOSITORY ON SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_ENGINEER;
-- models
GRANT CREATE MODEL ON SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_ENGINEER;
-- model monitors
GRANT CREATE MODEL MONITOR ON SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_ENGINEER;
-- pipes
GRANT CREATE PIPE ON SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_ENGINEER;
-- procedures
GRANT CREATE PROCEDURE ON SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_ENGINEER;
-- semantic views
GRANT CREATE SEMANTIC VIEW ON SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_ENGINEER;
-- sequences
GRANT CREATE SEQUENCE ON SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_ENGINEER;
-- snapshots
GRANT CREATE SNAPSHOT ON SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_ENGINEER;
-- classification profiles
GRANT CREATE SNOWFLAKE.DATA_PRIVACY.CLASSIFICATION_PROFILE ON SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_ENGINEER;
-- classification
GRANT CREATE SNOWFLAKE.ML.CLASSIFICATION ON SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_ENGINEER;
-- forecast
GRANT CREATE SNOWFLAKE.ML.FORECAST ON SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_ENGINEER;
-- stage
GRANT CREATE STAGE ON SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_ENGINEER;
-- streams
GRANT CREATE STREAM ON SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_ENGINEER;
-- tables
GRANT CREATE TABLE ON SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_ENGINEER;
-- tags
GRANT CREATE TAG ON SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_ENGINEER;
-- tasks
GRANT CREATE TASK ON SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_ENGINEER;
-- temporary tables
GRANT CREATE TEMPORARY TABLE ON SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_ENGINEER;

-- monitor grants
-- dynamic tables
GRANT MONITOR ON ALL DYNAMIC TABLES IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_ENGINEER;
GRANT MONITOR ON FUTURE DYNAMIC TABLES IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_ENGINEER;
-- functions
GRANT MONITOR ON ALL FUNCTIONS IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_ENGINEER;
GRANT MONITOR ON FUTURE FUNCTIONS IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_ENGINEER;
-- iceberg tables
GRANT MONITOR ON ALL ICEBERG TABLES IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_ENGINEER;
GRANT MONITOR ON FUTURE ICEBERG TABLES IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_ENGINEER;
-- pipes
GRANT MONITOR ON ALL PIPES IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_ENGINEER;
GRANT MONITOR ON FUTURE PIPES IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_ENGINEER;
-- procedures
GRANT MONITOR ON ALL PROCEDURES IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_ENGINEER;
GRANT MONITOR ON FUTURE PROCEDURES IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_ENGINEER;
-- semantic views
GRANT MONITOR ON ALL SEMANTIC VIEWS IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_ENGINEER;
GRANT MONITOR ON FUTURE SEMANTIC VIEWS IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_ENGINEER;

-- operate grants
-- dynamic tables
GRANT OPERATE ON ALL DYNAMIC TABLES IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_ENGINEER;
GRANT OPERATE ON FUTURE DYNAMIC TABLES IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_ENGINEER;
-- pipes
GRANT OPERATE ON ALL PIPES IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_ENGINEER;
GRANT OPERATE ON FUTURE PIPES IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_ENGINEER;

-- read grants
-- secrets
GRANT READ ON ALL SECRETS IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_ENGINEER;
GRANT READ ON FUTURE SECRETS IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_ENGINEER;
-- git repositories
GRANT READ ON ALL GIT REPOSITORIES IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_ENGINEER;
GRANT READ ON FUTURE GIT REPOSITORIES IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_ENGINEER;

-- rebuild grants
GRANT REBUILD ON ALL TABLES IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_ENGINEER;
GRANT REBUILD ON FUTURE TABLES IN SCHEMA GOVERNANCE.COMMON TO DATABASE ROLE GOVERNANCE.COMMON_ENGINEER;